"""
BrainTrader
------------------------
Full Nifty 500 Universe Database
"""

NIFTY50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "LT.NS", "BAJFINANCE.NS",
    "HINDUNILVR.NS", "AXISBANK.NS", "ASIANPAINT.NS", "KOTAKBANK.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "NTPC.NS", "POWERGRID.NS", "BAJAJFINSV.NS", "M&M.NS", "HCLTECH.NS"
]

BANKNIFTY = [
    "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS", 
    "KOTAKBANK.NS", "INDUSINDBK.NS", "PNB.NS", "BANKBARODA.NS"
]

NIFTY_MIDCAP = [
    "MIDHANI.NS", "TRENT.NS", "TVSMOTOR.NS", "JUBLFOOD.NS", "CUMMINSIND.NS",
    "FEDERALBNK.NS", "ASHOKLEY.NS", "MRF.NS", "VOLTAS.NS", "L&TFH.NS",
    "AUBANK.NS", "IDFCFIRSTB.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "LUPIN.NS",
    "PIIND.NS", "TATACHEM.NS", "M&MFIN.NS", "ASTRAL.NS", "BALKRISIND.NS",
    "BHARATFORG.NS", "CONCOR.NS", "COROMANDEL.NS", "CROMPTON.NS", "DIXON.NS",
    "ESCORTS.NS", "GUJGASLTD.NS", "HAL.NS", "IGL.NS", "INDIANB.NS",
    "INDUSTOWER.NS", "JINDALSTEL.NS", "LAURUSLABS.NS", "LICHSGFIN.NS", "MAXHEALTH.NS"
]

NIFTY_SMALLCAP = [
    "CDSL.NS", "RENUKA.NS", "SUZLON.NS", "IRFC.NS", "RVNL.NS",
    "ANGELONE.NS", "BSE.NS", "CYIENT.NS", "EQUITASBNK.NS", "HAPPSTMNDS.NS",
    "IEX.NS", "AMBER.NS", "BEML.NS", "BIRLACORPN.NS", "BLS.NS",
    "BSOFT.NS", "CAMPUS.NS", "CAMS.NS", "CASTROLIND.NS", "CENTURYPLY.NS",
    "CHAMBLFERT.NS", "CUB.NS", "DATAPATTNS.NS", "EASEMYTRIP.NS", "EIDPARRY.NS",
    "FSL.NS", "GLENMARK.NS", "GNFC.NS", "GRANULES.NS", "GSPL.NS"
]

NIFTY_MICROCAP = [
    "ZENTEC.NS", "ZOMATO.NS", "PAYTM.NS", "NYKAA.NS", "DELHIVERY.NS",
    "AWL.NS", "TRIDENT.NS", "UCOBANK.NS", "UTIAMC.NS", "VGUARD.NS",
    "WELSPUNIND.NS", "YESBANK.NS", "ZFCVINDIA.NS", "ZYDUSLIFE.NS", "AARTIDRUGS.NS",
    "AARTIIND.NS", "AAVAS.NS", "ABB.NS", "ABBOTINDIA.NS", "ABCAPITAL.NS",
    "ABFRL.NS", "ACC.NS", "ADANIPOWER.NS", "ADANIGREEN.NS", "ADANIENSOL.NS",
    "AEGISCHEM.NS", "AETHER.NS", "AFFLE.NS", "AJANTPHARM.NS", "ALEMBICLTD.NS",
    "ALKEM.NS", "ALKYLAMINE.NS", "ALLCARGO.NS", "ALOKINDS.NS", "AMARAJABAT.NS",
    "ANURAS.NS", "APARINDS.NS", "APOLLOTYRE.NS", "APTUS.NS", "ASAHIINDIA.NS",
    "ASTRAZEN.NS", "ATUL.NS", "AVANTIFEED.NS", "BAJAJELEC.NS", "BALAMINES.NS",
    "BALRAMCHIN.NS", "BANARISUG.NS", "BANKINDIA.NS", "BANKMAHAB.NS", "BATAINDIA.NS",
    "BAYERCROP.NS", "BDL.NS", "BEL.NS", "BEML.NS", "BGRENERGY.NS",
    "BHARATRAS.NS", "BIOCON.NS", "BSE.NS", "CANBK.NS", "CANFINHOME.NS",
    "CARBORUNIV.NS", "CASTROLIND.NS", "CEATLTD.NS", "CENTRALBK.NS", "CENTURYTEX.NS",
    "CERA.NS", "CESC.NS", "CGPOWER.NS", "CHALET.NS", "CHENNPETRO.NS",
    "CHOLAHLDNG.NS", "CIEINDIA.NS", "CITYUNION.NS", "CLEAN.NS", "COCHINSHIP.NS",
    "COFORGE.NS", "COLPAL.NS", "COMPINFO.NS", "CONCOR.NS", "COROMANDEL.NS",
    "CRAFTSMAN.NS", "CREDITACC.NS", "CRISIL.NS", "CSBBANK.NS", "CUB.NS",
    "CUMMINSIND.NS", "CYIENT.NS", "DALBHARAT.NS", "DATAPATTNS.NS", "DBCORP.NS",
    "DCMSHRIRAM.NS", "DEEPAKNTR.NS", "DELTACORP.NS", "DEVYANI.NS", "DHANI.NS",
    "EASEMYTRIP.NS", "EIDPARRY.NS", "EIHOTEL.NS", "ELGIEQUIP.NS", "EMAMILTD.NS",
    "ENDURANCE.NS", "ENGINERSIN.NS", "EPL.NS", "EQUITASBNK.NS", "ERIS.NS",
    "ESCORTS.NS", "EXIDEIND.NS", "FACT.NS", "FDC.NS", "FINCABLES.NS"
]

MY_WATCHLIST = []